dbfilename redis_cache.rdb
dir /home/neemus/frappe-bench-new/config/pids
pidfile /home/neemus/frappe-bench-new/config/pids/redis_cache.pid
bind 127.0.0.1
port 13002
maxmemory 1197mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /home/neemus/frappe-bench-new/config/redis_cache.acl
