dbfilename redis_queue.rdb
dir /home/neemus/frappe-bench-new/config/pids
pidfile /home/neemus/frappe-bench-new/config/pids/redis_queue.pid
bind 127.0.0.1
port 12002

aclfile /home/neemus/frappe-bench-new/config/redis_queue.acl
